platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

#tools
pod 'SnapKit', '~> 0.16'
pod 'PromiseKit/CorePromise', '~> 3.0'
pod 'FBSDKCoreKit', '~> 4.9'
pod 'FBSDKLoginKit', '~> 4.9'
pod 'Gloss', '~> 0.7'
pod 'AsyncSwift', '~> 1.6'
pod 'Alamofire', '~> 3.1'
pod 'Timepiece', '~> 0.4'
pod 'Timberjack', '~> 0.0'
pod 'HanekeSwift', '~> 0.10'

#UI
pod 'RAMAnimatedTabBarController', '~> 1.2.2'
pod 'Koloda', '~> 2.0'
pod 'AFImageHelper', '~> 3.0'
pod 'PKHUD', '~> 3.1'


post_install do |installer|
    `find Pods -regex 'Pods/pop.*\\.h' -print0 | xargs -0 sed -i '' 's/\\(<\\)pop\\/\\(.*\\)\\(>\\)/\\"\\2\\"/'`
end